service: vf-challenge
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
functions:
  getDadJoke:
    handler: getDadJoke.getDadJoke
  getWeather:
    handler: getWeather.getWeather
    environment:
      WEATHER_APP_ID: ${env:WEATHER_APP_ID}
